cd /usr/local/redis-cluster/redis7001/bin
./redis-server ../redis.conf
cd /usr/local/redis-cluster/redis7002/bin
./redis-server ../redis.conf
cd /usr/local/redis-cluster/redis7003/bin
./redis-server ../redis.conf
cd /usr/local/redis-cluster/redis7004/bin
./redis-server ../redis.conf
cd /usr/local/redis-cluster/redis7005/bin
./redis-server ../redis.conf
cd /usr/local/redis-cluster/redis7006/bin
./redis-server ../redis.conf
